---
services:
  devenv:
    image: devenv
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "2300:2300"
    volumes:
      - .:/devenv
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:

