---
services:
  dev:
    image: devenv
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "2300:2300" # Hanami
#      - "1234:1234" # RubyMine
#      - "26162:26162" # RubyMine
    volumes:
      - .:/devenv
    command:
      - /bin/bash
      - -c
      - sleep infinity
  db:
    profiles:
      - postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:

